<?php

/**
 * Poke™
 *
 * Joonatan Juustoraaste > Harakiri > Kamikaze > Poke
 * Quick 'n' dirty Apache auth generator
 *
 * @usage: Upload and run. Make sure files are writable, etc.
 */

$pre_warnings = array();

$htaccess_file_path = '.htaccess';
$server_root        = str_replace('poke.php', '', $_SERVER['SCRIPT_FILENAME']);
$htpassw_file_path  = $server_root . '.htpassw';

// Check if we have an existing .htpassw file
if(file_exists($htpassw_file_path))
{
	$pre_warnings[] = '.htpassw file already exists';
}

// Check if we have a .htaccess file
$htaccess_exists = file_exists($htaccess_file_path);

// Make sure it's writeable
$htaccess_is_writable = is_writable($htaccess_file_path);

// If it isn't writable AND it does indeed exist, we have a problem
if( ! $htaccess_is_writable and $htaccess_exists === true)
{
	$pre_warnings[] = '.htaccess file is not writable';
}

// ---------------------------------------------------------------------------

if(isset($_GET['do']))
{
	// Let's get to business...

	$crypt_passwd     = true;
	$create_memo_file = true;

	// Check that we have a username and a password
	$post = $_POST['creds'];

	if(empty($post['username']) or empty($post['password']))
	{
		die('You need to provide both a username and a password');
	}

	$username = trim($post['username']);
	$password = trim($post['password']);

	$plaintext_password = $password;

	if($crypt_passwd === true)
	{
		$password = crypt($password);
	}

	$data = array();

	$data['htaccess'] = '
# --- Start generated by Poke ---
AuthUserFile ' . $htpassw_file_path . '
AuthType Basic
AuthName "Protected directory"
Require valid-user
# --- End generated by Poke ---
	';

	$data['htpasswd'] = $username . ':' . $password;

	file_put_contents($htaccess_file_path, $data['htaccess'], FILE_APPEND);
	file_put_contents($htpassw_file_path, $data['htpasswd'], FILE_APPEND);

	if($create_memo_file === true)
	{
		$create_memo_data = '<?php
/*
Username: ' . $username . '
Password: ' . $plaintext_password . '
*/';
		file_put_contents('LOGIN_MEMO.php', $create_memo_data); // TODO: Isn't working?
	}

	die('Done.');
}

?><!doctype html>
<html>
<head>
<meta charset='utf-8'>
<title>Poke</title>
<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js'></script>
<script type='text/javascript'>

var Poke = function() {

	this.init = function()
	{
		randomizePassword();
	};

	var randomString = function(string_length)
	{
		var chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz@!?.,";
		var randomstring = '';
		for (var i=0; i<string_length; i++) {
			var rnum = Math.floor(Math.random() * chars.length);
			randomstring += chars.substring(rnum,rnum+1);
		}
		return randomstring;
	}

	var randomizePassword = function()
	{
		$('#password_field').val(randomString(12));
	};

};

$(function()
{
	var P = new Poke();
		P.init();
});

</script>
<style type="text/css" media="screen">
body { padding: 30px; font-family: Arial; font-size: 12px; }
input { display: block; }
</style>
</head>
<body>
<h1>Poke™</h1>

<?php if( ! empty($pre_warnings)): ?>
<h2>Warnings:</h2>
<ul>
	<?php
	foreach($pre_warnings as $i)
	{
		echo '
			<li>' . $i . '</li>
		';
	}
	?>
</ul>
<?php else: ?>
<form method='post' action='poke.php?do' id='poke_form'>
	<p><label>Username<input type='text' name='creds[username]' /></label></p>
	<p><label>Password<input type='text' name='creds[password]' id='password_field' /></label></p>
	<p><input type='submit' value='Ok'/></p>
</form> <!-- poke_form -->
<?php endif; ?>

</body>
</html>